import { AppData } from "@/types/app-data";

export const appData: AppData = {
  technical_data: [
    {
      pump_id: "P-001",
      pump_type: "Centrifugal",
      capacity_lps: 50,
      head_m: 22,
      power_kw: 15,
      voltage_v: 415,
      current_a: 28,
      commissioning_year: 2020,
      manufacturer: "KSB",
      model: "Etanorm G50-032",
      location: "Pump House 1",
    },
    {
      pump_id: "P-002",
      pump_type: "Centrifugal",
      capacity_lps: 27.2,
      head_m: 18,
      power_kw: 10,
      voltage_v: 415,
      current_a: 18.5,
      commissioning_year: 2019,
      manufacturer: "Grundfos",
      model: "CR 64-2",
      location: "Pump House 1",
    },
    {
      pump_id: "P-003",
      pump_type: "Submersible",
      capacity_lps: 35,
      head_m: 45,
      power_kw: 20,
      voltage_v: 415,
      current_a: 37,
      commissioning_year: 2021,
      manufacturer: "Crompton Greaves",
      model: "SLIP 150",
      location: "Borehole 1",
    },
    {
      pump_id: "M-001",
      pump_type: "Motor",
      capacity_lps: 0,
      head_m: 0,
      power_kw: 15,
      voltage_v: 415,
      current_a: 28,
      commissioning_year: 2020,
      manufacturer: "Siemens",
      model: "1LE1001",
      location: "Pump House 1",
    },
    {
      pump_id: "M-002",
      pump_type: "Motor",
      capacity_lps: 0,
      head_m: 0,
      power_kw: 10,
      voltage_v: 415,
      current_a: 18.5,
      commissioning_year: 2019,
      manufacturer: "ABB",
      model: "M3BP",
      location: "Pump House 1",
    },
  ],
  operation_data: [
    {
      timestamp: "2025-09-15 08:00:00",
      pump_id: "P-001",
      status: "Running",
      flow_rate_lps: 48.5,
      head_m: 21.5,
      current_a: 27.2,
      voltage_v: 412,
      power_kw: 14.2,
      temperature_c: 45,
      vibration_mm_s: 1.2,
      bearing_temp_c: 52,
    },
    {
      timestamp: "2025-09-15 08:00:00",
      pump_id: "P-002",
      status: "Running",
      flow_rate_lps: 28.7,
      head_m: 17.8,
      current_a: 18.9,
      voltage_v: 415,
      power_kw: 10.5,
      temperature_c: 42,
      vibration_mm_s: 0.9,
      bearing_temp_c: 48,
    },
    {
      timestamp: "2025-09-15 08:00:00",
      pump_id: "P-003",
      status: "Stopped",
      flow_rate_lps: 0,
      head_m: 0,
      current_a: 0,
      voltage_v: 0,
      power_kw: 0,
      temperature_c: 28,
      vibration_mm_s: 0,
      bearing_temp_c: 30,
    },
  ],
  spare_parts: [
    {
      part_id: "SP-001",
      description: "Impeller - 8x6",
      pump_model: "Etanorm G50-032",
      quantity: 3,
      min_stock: 2,
      unit_cost: 45000,
      supplier: "KSB India",
      status: "In Stock",
    },
    {
      part_id: "SP-002",
      description: "Mechanical Seal",
      pump_model: "Etanorm G50-032",
      quantity: 5,
      min_stock: 2,
      unit_cost: 18000,
      supplier: "John Crane India",
      status: "In Stock",
    },
    {
      part_id: "SP-003",
      description: "Bearing - 6308",
      pump_model: "All",
      quantity: 8,
      min_stock: 3,
      unit_cost: 3500,
      supplier: "SKF",
      status: "In Stock",
    },
    {
      part_id: "SP-004",
      description: "O-Ring Set",
      pump_model: "All",
      quantity: 15,
      min_stock: 5,
      unit_cost: 1200,
      supplier: "Parker Hannifin",
      status: "In Stock",
    },
    {
      part_id: "SP-005",
      description: "Coupling",
      pump_model: "CR 64-2",
      quantity: 2,
      min_stock: 1,
      unit_cost: 12000,
      supplier: "Grundfos",
      status: "In Stock",
    },
    {
      part_id: "SP-006",
      description: "Motor Winding",
      pump_model: "1LE1001",
      quantity: 0,
      min_stock: 1,
      unit_cost: 25000,
      supplier: "Siemens",
      status: "Low Stock",
    },
  ],
  maintenance_records: [
    {
      record_id: "MR-001",
      pump_id: "P-001",
      date: "2025-08-20",
      type: "Preventive",
      description: "Routine maintenance - Bearing replacement",
      parts_used: ["SP-003"],
      cost: 8500,
      technician: "Rajesh Kumar",
      status: "Completed",
    },
    {
      record_id: "MR-002",
      pump_id: "P-002",
      date: "2025-09-01",
      type: "Corrective",
      description: "Mechanical seal replacement due to leakage",
      parts_used: ["SP-002"],
      cost: 22000,
      technician: "Suresh Patel",
      status: "Completed",
    },
    {
      record_id: "MR-003",
      pump_id: "P-003",
      date: "2025-09-10",
      type: "Preventive",
      description: "Annual servicing and inspection",
      parts_used: ["SP-004"],
      cost: 5200,
      technician: "Amit Singh",
      status: "Completed",
    },
    {
      record_id: "MR-004",
      pump_id: "P-001",
      date: "2025-09-25",
      type: "Preventive",
      description: "Scheduled quarterly maintenance",
      parts_used: [],
      cost: 3000,
      technician: "Rajesh Kumar",
      status: "Scheduled",
    },
  ],
};
